# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
  - job: Build
    strategy:
     matrix:
      Windows:
        vmImage: windows-latest
      Linux:
        vmImage: ubuntu-latest
      Mac:
        vmImage: macos-latest
    pool:
      vmImage: $(vmImage)

    variables:
    - group: PrivateNugetFeedVariables

    steps:
    - script: echo $(testVariable)
      displayName: Test variables are working

    - script: dotnet restore -v:d
      displayName: Restore

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        arguments: '--no-restore'
