trigger:
- main
pr:
- main

jobs:
  - job: Build
    strategy:
     matrix:
      Windows:
        vmImage: windows-latest
      Linux:
        vmImage: ubuntu-latest
      Mac:
        vmImage: macos-latest
    pool:
      vmImage: $(vmImage)

    variables:
    - group: PrivateNugetFeedVariables

    steps:
    - script: dotnet restore -v:d
      displayName: Restore
      env:
        NuGetFeedUserName: $(NuGetFeedUserName)
        NuGetFeedPAT: $(NuGetFeedPAT)

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        arguments: '--no-restore'
